plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
lsi: false
safe: true
source: /workspaces/HC26-Burchett-Matt-Senior-Project/docs
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: andrewbanchich/forty-jekyll-theme