name: Pages deploy

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - run: bundle install
      working-directory: ./docs
    - run: bundle exec jekyll build
      working-directory: ./docs
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs/_site'